name: Manual Hello Trigger

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # This fixes the "not a git repository" error

      - name: Print Hello
        run: echo "Hello, world!"

      - name: Trigger Deployment
        run: |
          gh workflow run "sagarpanda.com" --ref main
